language: haxe

os:
  - linux

haxe:
  - "4.0.0-rc.5"
  - development

matrix:
  allow_failures:
    - haxe: "development"

branches:
  only:
  - master
  - r2

install:
  - haxelib install hxnodejs
  - haxelib install utest
  - haxelib dev hxmpp .

script:
  - haxe build.hxml
  - haxe haxedoc.hxml
  - haxe test.hxml
  # TODO: run tests
